### ISSUE TITLE
Connecting Drive with the Website

### ISSUE THREAD

**Issue by claudiakoeppen** [misterfresh/react-drive-cms#7]
Hi, I am able to make any customizations to the website after following the instructions, but am having trouble connecting my posts to the website. Right now, the website shows that the posts and categories are empty. I have published the dashboard as a webpage, and tried different variations of turning on/off the sharable link. Any help would be greatly appreciated!

**Comment by therrou** [comment]
Hello Claudia, how are you? I have the same issue. I can pull the data from the Google spreadsheet, but I can not render the image. I pull for example '5.jpg' instead of the link.

**Comment by misterfresh** [comment]
@claudiakoeppen Make sure that the Google Docs documents that you create are set to Sharing options: "Public, Anyone can access with the link". The React app is not logged-in when it tries to access your Drive data, so everything has to be public. If the Posts and Categories are empty, it means that the call to read the contents of your Dashboard spreadsheet is failing. That spreadsheet needs to be set to public as well. 

In Google Chrome press F12 to access Developer Tools and check the Network tab. Reload the homepage. Check the request that starts with "https://spreadsheets.google.com/feeds/list/" and why it is failing (probably because the spreadsheet is not set to public).

**Comment by misterfresh** [comment]
Added step by step instructions to help with connecting Drive: https://github.com/misterfresh/react-drive-cms/blob/master/GUIDE.md .

**Comment by therrou** [comment]
Hello Antoine, how are you? thank you so much for taking the time of answer
me. Today I will work on the implementation of your tool. Is very useful
and practical for the people that want to post in a Blog.
